<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateMakananTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('makanan', function (Blueprint $table) {
            $table->increments('id');
            $table->string('nama');
            $table->string('kode_isi')->nullable();
            $table->integer('harga')->nullable();
            $table->string('jenis')->nullable();
            $table->integer('id_dapur');
            $table->timestamps();
        });

        DB::table('makanan')->insert(array(
            ['nama'     => 'Paket A',
             'kode_isi' => '1011',
             'harga'    => 6000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 1],
            ['nama'     => 'Paket B',
             'kode_isi' => '10111',
             'harga'    => 7000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 1],
            ['nama'     => 'Paket C',
             'kode_isi' => '10111',
             'harga'    => 7000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 1],
            ['nama'     => 'Paket D',
             'kode_isi' => '10111',
             'harga'    => 8500,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 1],
            ['nama'     => 'Paket E',
             'kode_isi' => '1011101',
             'harga'    => 12000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 1],
            ['nama'     => 'Paket A',
             'kode_isi' => '-',
             'harga'    => 8000,
             'jenis'    => 'Hemat Foam',
             'id_dapur' => 1],
            ['nama'     => 'Paket B',
             'kode_isi' => '010011',
             'harga'    => 11500,
             'jenis'    => 'Hemat Foam',
             'id_dapur' => 1],
            ['nama'     => 'Paket C',
             'kode_isi' => '1110',
             'harga'    => 8000,
             'jenis'    => 'Hemat Foam',
             'id_dapur' => 1],
            ['nama'     => 'Paket D',
             'kode_isi' => '1101',
             'harga'    => 11500,
             'jenis'    => 'Hemat Foam',
             'id_dapur' => 1],
            ['nama'     => 'Paket A',
             'kode_isi' => '1110',
             'harga'    => 13000,
             'jenis'    => 'Hemat Kotak',
             'id_dapur' => 1],
            ['nama'     => 'Paket B',
             'kode_isi' => '1011',
             'harga'    => 13000,
             'jenis'    => 'Hemat Kotak',
             'id_dapur' => 1],
            ['nama'     => 'Paket C',
             'kode_isi' => '111',
             'harga'    => 13000,
             'jenis'    => 'Hemat Kotak',
             'id_dapur' => 1],
            ['nama'     => 'Nasi Rendang',
             'kode_isi' => '1111',
             'harga'    => 15500,
             'jenis'    => 'Happy Komplit',
             'id_dapur' => 1],
            ['nama'     => 'Nasi Rames',
             'kode_isi' => '10111',
             'harga'    => 15500,
             'jenis'    => 'Happy Komplit',
             'id_dapur' => 1],
            ['nama'     => 'Nasi Uduk',
             'kode_isi' => '111',
             'harga'    => 15500,
             'jenis'    => 'Happy Komplit',
             'id_dapur' => 1],
            ['nama'     => 'Nasi Urap',
             'kode_isi' => '11011',
             'harga'    => 15500,
             'jenis'    => 'Happy Komplit',
             'id_dapur' => 1],
            ['nama'     => 'Nasi Kuning',
             'kode_isi' => '1101111',
             'harga'    => 19500,
             'jenis'    => 'Happy Komplit',
             'id_dapur' => 1],
            ['nama'     => 'Paket 10 Orang',
             'kode_isi' => '-',
             'harga'    => 205000,
             'jenis'    => 'Tumpeng',
             'id_dapur' => 1],
            ['nama'     => 'Paket 20 Orang',
             'kode_isi' => '-',
             'harga'    => 400000,
             'jenis'    => 'Tumpeng',
             'id_dapur' => 1],
            ['nama'     => 'Paket 30 Orang',
             'kode_isi' => '-',
             'harga'    => 550000,
             'jenis'    => 'Tumpeng',
             'id_dapur' => 1],
            ['nama'     => 'Paket 1',
             'kode_isi' => '0100000000010001000',
             'harga'    => 5500,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 2],
            ['nama'     => 'Paket 2',
             'kode_isi' => '01000000000101000',
             'harga'    => 7500,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 2],
            ['nama'     => 'Paket 3',
             'kode_isi' => '010000000001010001000',
             'harga'    => 8000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 2],
            ['nama'     => 'Paket 4',
             'kode_isi' => '010100010000000001000',
             'harga'    => 7000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 2],
            ['nama'     => 'Paket 5',
             'kode_isi' => '010100010000000001000',
             'harga'    => 8000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 2],
            ['nama'     => 'Paket 6',
             'kode_isi' => '0100000000011000',
             'harga'    => 9500,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 2],
            ['nama'     => 'Paket Hemat',
             'kode_isi' => '0',
             'harga'    => 7000,
             'jenis'    => 'Nasi Foam',
             'id_dapur' => 2],
            ['nama'     => 'Paket 1',
             'kode_isi' => '01000000000100010000001000',
             'harga'    => 9000,
             'jenis'    => 'Nasi Foam',
             'id_dapur' => 2],
            ['nama'     => 'Nasi Geprek',
             'kode_isi' => '100000000011',
             'harga'    => 10000,
             'jenis'    => 'Nasi Foam',
             'id_dapur' => 2],
            ['nama'     => 'Paket 2',
             'kode_isi' => '01000000000100010000010001',
             'harga'    => 12000,
             'jenis'    => 'Nasi Kotak',
             'id_dapur' => 2],
            ['nama'     => 'Paket 3',
             'kode_isi' => '010000000001000100000100011',
             'harga'    => 14000,
             'jenis'    => 'Nasi Kotak',
             'id_dapur' => 2],
            ['nama'     => 'Paket 4',
             'kode_isi' => '0100000000010001000001000111',
             'harga'    => 15000,
             'jenis'    => 'Nasi Kotak',
             'id_dapur' => 2],
            ['nama'     => 'Paket 5',
             'kode_isi' => '01000000000100010000010001111',
             'harga'    => 17000,
             'jenis'    => 'Nasi Kotak',
             'id_dapur' => 2],
            ['nama'     => 'Paket 10 Orang',
             'kode_isi' => '-',
             'harga'    => 185000,
             'jenis'    => 'Tumpeng',
             'id_dapur' => 2],
            ['nama'     => 'Paket 1',
             'kode_isi' => '1110',
             'harga'    => 7000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 4],
            ['nama'     => 'Paket 2',
             'kode_isi' => '111',
             'harga'    => 9000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 4],
            ['nama'     => 'Paket 3',
             'kode_isi' => '111',
             'harga'    => 10000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 4],
            ['nama'     => 'Paket 4',
             'kode_isi' => '111',
             'harga'    => 9000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 4],
            ['nama'     => 'Paket 5',
             'kode_isi' => '111',
             'harga'    => 10000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 4],
            ['nama'     => 'Paket 6',
             'kode_isi' => '111',
             'harga'    => 10000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 4],
            ['nama'     => 'Paket 7',
             'kode_isi' => '111',
             'harga'    => 11000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 4],
            ['nama'     => 'Paket 8',
             'kode_isi' => '111',
             'harga'    => 13000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 4],
            ['nama'     => 'Paket 9',
             'kode_isi' => '111',
             'harga'    => 14000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 4],
            ['nama'     => 'Paket 10',
             'kode_isi' => '1110000',
             'harga'    => 14000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 4],
            ['nama'     => 'Paket 11',
             'kode_isi' => '111',
             'harga'    => 16000,
             'jenis'    => 'Nasi Bungkus',
             'id_dapur' => 4],
            ['nama'     => 'Paket 1',
             'kode_isi' => '11110',
             'harga'    => 15000,
             'jenis'    => 'Nasi Kotak',
             'id_dapur' => 4],
            ['nama'     => 'Paket 2',
             'kode_isi' => '11111',
             'harga'    => 17000,
             'jenis'    => 'Nasi Kotak',
             'id_dapur' => 4],
            ['nama'     => 'Paket 1',
             'kode_isi' => '11110',
             'harga'    => 15000,
             'jenis'    => 'Nasi Foam',
             'id_dapur' => 4],
            ['nama'     => 'Paket 2',
             'kode_isi' => '11111',
             'harga'    => 17000,
             'jenis'    => 'Nasi Foam',
             'id_dapur' => 4],
            ['nama'     => 'Putih 10',
             'kode_isi' => '-',
             'harga'    => 185000,
             'jenis'    => 'Tumpeng',
             'id_dapur' => 4],
            ['nama'     => 'Kuning 10',
             'kode_isi' => '-',
             'harga'    => 195000,
             'jenis'    => 'Tumpeng',
             'id_dapur' => 4],
            ['nama'     => 'Putih 20',
             'kode_isi' => '-',
             'harga'    => 500000,
             'jenis'    => 'Tumpeng',
             'id_dapur' => 4],
            ['nama'     => 'Kuning 20',
             'kode_isi' => '-',
             'harga'    => 500000,
             'jenis'    => 'Tumpeng',
             'id_dapur' => 4]
        ));

        DB::disableQueryLog();
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('makanan');
    }
}
